# Generated by Django 5.1 on 2024-08-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pruebaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('email', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'test_table',
            },
        ),
        migrations.DeleteModel(
            name='MyModel',
        ),
    ]
